<?php

 $apiKey = "rzp_test_ZymubfNUVDnrp3";

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="./success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_ZymubfNUVDnrp3" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amount'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="HAPPYFACE Sparks Foundation"
    data-description="Donate "
    data-image="https://cdn.vox-cdn.com/thumbor/VM9qJlfkrS4EQqELf1yBzlojEto=/0x0:2040x1360/925x925/filters:focal(857x517:1183x843):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/67653419/acastro_201016_1777_moonbug_0002.0.jpg"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['mobile'];?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

